### ISSUE TITLE
Converting models with textured meshes in model ruins the texture

### ISSUE THREAD

**Issue by TyNoOutlet** [ExperiencersInternational/FolderTool#12]
Not sure why this happens and I can't check rn so leaving this here.

As you can see, before:
![image](https://user-images.githubusercontent.com/74572291/155527303-007c2bec-b644-4456-8d27-b97a302550f2.png)
and after:
![image](https://user-images.githubusercontent.com/74572291/155527374-3d4ddbf0-6458-40aa-947d-298f0ceb4301.png)

**Comment by ExperiencersInternational** [comment]
@csqrl can you help?

**Comment by TyNoOutlet** [comment]
@ExperiencersInternational looking at the src right now, I think it's because you're using GetDescendants instead of GetChildren.

It's a really simple fix and it would honestly be more of a hassle for me to fork and ix it, could you do that?

**Comment by csqrl** [comment]
https://github.com/ExperiencersInternational/FolderTool/blob/e0945d7fbe7b3d09297bcd50c548740361ae79ae/src/ServerStorage/Main.server.lua#L99-L119

> @ExperiencersInternational looking at the src right now, I think it's because you're using GetDescendants instead of GetChildren.

this seems probable. consider changing to this:

```lua
for _, object in ipairs(selectedObjects) do
  if object.ClassName ~= "Model" then
    continue
  end

  local folder = Instance.new("Folder")
  folder.Name = object.Name

  for _, child in ipairs(object:GetChildren()) do
    child.Parent = folder
  end

  folder.Parent = object.Parent
  object:Destroy()
end
```

**Comment by ExperiencersInternational** [comment]
Will implement when I have time after RGDC or something, thanks @csqrl as always

**Comment by ExperiencersInternational** [comment]
Fixed this, will be pulling changes over to GitHub soon.
